// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxdtwqgjgzrxgckyszth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZHR3cWdqZ3pyeGdja3lzenRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMDA5MTYsImV4cCI6MjA3NjY3NjkxNn0.bAvxSkd5Fsw5Daft3xDanjkovDb6WggHRTM8QnK5gD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});